spring:
  application:
    name: gateway_service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: gateway_service
        register: true
        enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: supplier_central_route
              uri: lb://supplier-central
              predicates:
                - Path=/suppliers/**
              filters:
                - StripPrefix=1
            - id: products_route
              uri: lb://product-catalogue-service
              predicates:
                - Path=/products/**
              filters:
                - StripPrefix=1
